import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { spawnSync } from 'node:child_process'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const SHOW_DIFF = process.argv.includes('--show-diff')

const PAIRS = [
  {
    name: 'smart-plan shared -> miniapp',
    left: 'shared/smart-plan.cjs',
    right: 'miniprogram/utils/smart-plan.js',
    maxChangedLines: 0,
    generated: true
  },
  {
    name: 'smart-plan shared -> web',
    left: 'shared/smart-plan.cjs',
    right: 'web/lib/smart-plan.cjs',
    maxChangedLines: 0,
    generated: true
  },
  {
    name: 'smart-plan platform pair',
    left: 'miniprogram/utils/smart-plan.js',
    right: 'web/lib/smart-plan.cjs',
    maxChangedLines: 0
  },
  {
    name: 'schedule-core shared -> miniapp',
    left: 'shared/schedule-core.cjs',
    right: 'miniprogram/utils/generated/schedule-core.js',
    maxChangedLines: 0,
    generated: true
  },
  {
    name: 'schedule-core shared -> web',
    left: 'shared/schedule-core.cjs',
    right: 'web/lib/shared/schedule-core.cjs',
    maxChangedLines: 0,
    generated: true
  },
  {
    name: 'schedule-core platform pair',
    left: 'miniprogram/utils/generated/schedule-core.js',
    right: 'web/lib/shared/schedule-core.cjs',
    maxChangedLines: 0
  },
  {
    name: 'schedule platform pair',
    left: 'miniprogram/utils/schedule.js',
    right: 'web/lib/schedule.cjs',
    maxChangedLines: 100
  }
]

function toPosix(filePath) {
  return filePath.split(path.sep).join('/')
}

function stripSyncHeader(content) {
  const lines = content.replace(/\r\n/g, '\n').split('\n')
  let index = 0
  while (index < lines.length) {
    const line = lines[index]
    if (
      /^\/\/ @(generated-from|paired-with|platform-divergence):?/.test(line) ||
      /^\/\/ Do not edit this file directly\./.test(line) ||
      line === ''
    ) {
      index += 1
      continue
    }
    break
  }
  return lines.slice(index).join('\n').replace(/\s*$/, '\n')
}

function readHeader(content) {
  const header = {}
  content.replace(/\r\n/g, '\n').split('\n').forEach(line => {
    const paired = line.match(/^\/\/ @paired-with\s+(.+)$/)
    if (paired) {
      header.pairedWith = paired[1].trim()
    }
    const generated = line.match(/^\/\/ @generated-from\s+(.+)$/)
    if (generated) {
      header.generatedFrom = generated[1].trim()
    }
    const divergence = line.match(/^\/\/ @platform-divergence:\s*(.*)$/)
    if (divergence) {
      header.divergence = divergence[1].trim()
    }
  })
  return header
}

function countChangedLines(diffText) {
  return diffText
    .split('\n')
    .filter(line => /^[+-]/.test(line) && !/^(---|\+\+\+)/.test(line))
    .length
}

async function diffNormalized(pair) {
  const tmpDir = await mkdtemp(path.join(os.tmpdir(), 'festival-sync-'))
  try {
    const leftPath = path.join(ROOT, pair.left)
    const rightPath = path.join(ROOT, pair.right)
    const leftRaw = await readFile(leftPath, 'utf8')
    const rightRaw = await readFile(rightPath, 'utf8')
    const left = path.join(tmpDir, 'left.js')
    const right = path.join(tmpDir, 'right.js')
    await writeFile(left, stripSyncHeader(leftRaw), 'utf8')
    await writeFile(right, stripSyncHeader(rightRaw), 'utf8')

    const result = spawnSync('diff', [
      '-u',
      '--label',
      pair.left,
      '--label',
      pair.right,
      left,
      right
    ], { encoding: 'utf8' })

    return {
      diff: result.stdout || '',
      changedLines: countChangedLines(result.stdout || ''),
      leftHeader: readHeader(leftRaw),
      rightHeader: readHeader(rightRaw)
    }
  } finally {
    await rm(tmpDir, { recursive: true, force: true })
  }
}

function validateHeader(pair, side, header, expectedPair) {
  const errors = []
  if (side !== 'shared' && !header.pairedWith) {
    errors.push(`${side} missing @paired-with`)
  }
  if (expectedPair && header.pairedWith && header.pairedWith !== expectedPair) {
    errors.push(`${side} @paired-with is ${header.pairedWith}, expected ${expectedPair}`)
  }
  if (pair.generated && side !== 'shared' && !header.generatedFrom) {
    errors.push(`${side} missing @generated-from`)
  }
  if (pair.generated && side !== 'shared' && header.generatedFrom && header.generatedFrom !== pair.left) {
    errors.push(`${side} @generated-from is ${header.generatedFrom}, expected ${pair.left}`)
  }
  return errors
}

async function main() {
  let failed = false

  for (const pair of PAIRS) {
    const result = await diffNormalized(pair)
    const leftSide = pair.left.startsWith('shared/') ? 'shared' : pair.left
    const rightSide = pair.right
    const headerErrors = pair.generated
      ? validateHeader(pair, rightSide, result.rightHeader, null)
      : []
        .concat(validateHeader(pair, leftSide, result.leftHeader, pair.right))
        .concat(validateHeader(pair, rightSide, result.rightHeader, pair.left))

    const ok = result.changedLines <= pair.maxChangedLines && headerErrors.length === 0
    const status = ok ? 'OK' : 'FAIL'
    const divergence = result.leftHeader.divergence || result.rightHeader.divergence || 'none'
    console.log(`${status} ${pair.name}: ${result.changedLines}/${pair.maxChangedLines} changed lines; divergence=${divergence}`)

    if (headerErrors.length) {
      failed = true
      headerErrors.forEach(error => console.error(`  - ${error}`))
    }
    if (result.changedLines > pair.maxChangedLines) {
      failed = true
      const hint = pair.generated ? 'Run `node scripts/sync-shared.mjs`.' : 'Review the platform divergence or raise the threshold deliberately.'
      console.error(`  - drift exceeds threshold. ${hint}`)
      if (SHOW_DIFF || pair.maxChangedLines === 0) {
        console.error(result.diff.split('\n').slice(0, 160).join('\n'))
      }
    }
  }

  if (failed) {
    process.exit(1)
  }
}

main().catch(error => {
  console.error(error)
  process.exit(1)
})
