import { mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

const GENERATED_FILES = [
  {
    source: 'shared/smart-plan.cjs',
    target: 'miniprogram/utils/smart-plan.js',
    pairedWith: 'web/lib/smart-plan.cjs',
    divergence: 'none'
  },
  {
    source: 'shared/smart-plan.cjs',
    target: 'web/lib/smart-plan.cjs',
    pairedWith: 'miniprogram/utils/smart-plan.js',
    divergence: 'none'
  },
  {
    source: 'shared/schedule-core.cjs',
    target: 'miniprogram/utils/generated/schedule-core.js',
    pairedWith: 'web/lib/shared/schedule-core.cjs',
    divergence: 'none'
  },
  {
    source: 'shared/schedule-core.cjs',
    target: 'web/lib/shared/schedule-core.cjs',
    pairedWith: 'miniprogram/utils/generated/schedule-core.js',
    divergence: 'none'
  }
]

function toPosix(filePath) {
  return filePath.split(path.sep).join('/')
}

function stripGeneratedHeader(content) {
  const lines = content.replace(/\r\n/g, '\n').split('\n')
  let index = 0
  while (index < lines.length) {
    const line = lines[index]
    if (
      /^\/\/ @(generated-from|paired-with|platform-divergence):?/.test(line) ||
      /^\/\/ Do not edit this file directly\./.test(line) ||
      line === ''
    ) {
      index += 1
      continue
    }
    break
  }
  return lines.slice(index).join('\n').replace(/\s*$/, '\n')
}

function generatedHeader(file) {
  return [
    `// @generated-from ${toPosix(file.source)}`,
    `// @paired-with ${toPosix(file.pairedWith)}`,
    `// @platform-divergence: ${file.divergence}`,
    '// Do not edit this file directly. Run `node scripts/sync-shared.mjs`.',
    ''
  ].join('\n')
}

async function main() {
  for (const file of GENERATED_FILES) {
    const sourcePath = path.join(ROOT, file.source)
    const targetPath = path.join(ROOT, file.target)
    const source = stripGeneratedHeader(await readFile(sourcePath, 'utf8'))
    const output = `${generatedHeader(file)}${source}`

    await mkdir(path.dirname(targetPath), { recursive: true })
    await writeFile(targetPath, output, 'utf8')
    console.log(`synced ${toPosix(file.source)} -> ${toPosix(file.target)}`)
  }
}

main().catch(error => {
  console.error(error)
  process.exit(1)
})
